# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Welcome to Liu Lab!
# Description of the Site
description: Explore RNA's mysteries in health and disease
# URL of Image of the Site
site-image: /assets/images/logo/logo_64_64_white.png
# Keywords of the Site
site-keywords: RNA modification
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/photos/3year.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: junliu1223@pku.edu.cn
facebook_username: thedevslot
twitter_username: thedevslot
instagram_username: thedevslot
linkedin_username: thedevslot
github_username:  thedevslot
youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Liu Lab
# URL for the Image of the Author
author-image: /assets/images/people/liujun.png
# 60 Words About the Author
author-about: Our laboratory is dedicated to investigate the molecular regulatory mechanisms and related biological functions of RNA modified/non-coding RNA. We use epigenetics, molecular biology, and high-throughput sequencing to explore the novel regulatory mechanisms of RNA modification/ncRNA on chromatin structure and gene transcription, and the biological functions of related regulatory pathways in embryonic stem cell differentiation, anti-tumor immunity, cancer and aging.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
